@base=http://localhost:5000/api/auth
@email=example@example.com
@password=SecurePassword123

### Authenticating user
POST {{base}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}