@base=http://localhost:5000

### Genre route teste
### Fetch all genres
@genre_id=genre_id
GET {{base}}/api/genres

### Fetch specific genre using ID
GET {{base}}/api/genres/{{genre_id}}

### Create new genre
POST {{base}}/api/genres/
Content-Type: application/json

{
  "name": "romance",
  "tags": [
    "tearjerker"
  ]
}

### Update genre using ID
PUT {{base}}/api/genres/{{genre_id}}
Content-Type: application/json

{
  "name": "rom-com"
}

### Self explanatory
DELETE {{base}}/api/genres/{{genre_id}}


### Customers route tests
### Fetch all customers
@customer_id=customer_id
GET {{base}}/api/customers

### Fetch specific customer using ID
GET {{base}}/api/customers/{{customer_id}}

### Create new customer
POST {{base}}/api/customers
Content-Type: application/json

{
  "isGold": true,
  "name": "Taylor Swift",
  "phone": "+5559876"
}

### Update existing customer based on ID. It is possible to update a single field, or multiple at once.
PUT {{base}}/api/customers/{{customer_id}}
Content-Type: application/json

{
  "isGold": false
}

### Delete customer from DB
DELETE {{base}}/api/customers/{{customer_id}}